### ISSUE TITLE
Issues with LEDs/force commands and strange startup lock

### ISSUE THREAD

**Issue by enricodente** [ForestMist/logitech-g27#3]
First of all, thanks Daniel for all this good work.
I am trying to use this library on a G27, but I am experiencing big issues, especially for the control commands.

All the commands reading work fine: I can read pedal percentage and buttons pressures, and print log events as confirmation.
Every command involving sending commands TO the G27 seems to be problematic instead: I cannot use LEDs (btw, there are some typos in the Wiki, somewhere there is led() instead of leds()). I cannot use forceConstant and many other "write" commands.
I tried to add some debug log into the catch for the leds() function, but the execution never seems to go there.

Also, there is a strange behavior at the connect() event: when I connect the G27 to the USB it calibrates and goes to middle position. After I launch my node script and simply do a connect(), the steering wheel will turn right by 90 degrees and will force that position, always. As previously said forceConstant or other functions do not have any effect.

If you need it I will be able to do whatever test, maybe it could be some different hardware revision? I have tested also older versions, before 1.0 with no success. 

Thank you in advance.

**Comment by ForestMist** [comment]
Thanks. ^_^

This sounds suspiciously like the issues that were happening with and were fixed in the G29 library. I think there is a good chance that bringing over those improvements will help here too. I'll work on that this week and let you know when it is ready for testing.

**Comment by enricodente** [comment]
Thank you very much! Available anytime for testing on G27 👍

**Comment by enricodente** [comment]
Hi Daniel,

Have you managed to give a look at the issue?

If you could tell me what to look for on the G29 library about the fix that solved this kind of problem I can also try to contribute.

Thanks.

**Comment by ForestMist** [comment]
Sorry for the delay.

I brought over the G29 wheel detection improvements. They are available here on GitHub and also on NPM (https://www.npmjs.com/package/logitech-g27). Version 1.0.5 of the logitech-g27 library is the one you'll want to try.

Let me know how it goes. ^_^

**Comment by enricodente** [comment]
Hi Daniel,
no worries. I have tested 1.0.5 but the behavior is still the same.

The problem is not in connecting to the device (I saw that you changed that part, detecting HW ID instead of peripheral name), the G27 always connects with no issues so far.

The issues are related to commands sent TO the G27 (LEDs command and everything involving motors) so everything that involves a "write", and that strange startup behavior, with the wheel turning 90 degrees right just after launching the node application.
Everything else regarding the "reading" from the G27 works fine (pedals percentage reading, steering wheel rotation sensing, buttons activations, ...).

Any clue?

**Comment by ForestMist** [comment]
Hmm, the issue really does sounds familiar but I can't remember why. #gettingold

Would you mind sharing your code so I can try it on my wheel? Either here or you can email github2 @ forestmist.org if you prefer.

**Comment by enricodente** [comment]
Hi Daniel,

I have really not much to show, I am just trying to get the hello world working for example.

g.connect(function(err) {
    g.on('pedals-gas', function(val) {
        g.leds(val)
        console.log(val);
    })
})

I have tried to connect to the steering wheel with and without 'options'.
I have tried to bind to the buttons or pedals events and write console.log with success, the returned value is correct. In the code above, the correct pedal value is printed in console.

I have tried also to drive leds with constant values (arrays, decimal values, ...) but no luck with every method.

In any case, everything involving READING from G27 works, while everything involving WRITING doesn't. Anytime I use for example g.leds(value) or g.forceConstant(value) I cannot get LEDs turning on or steering wheel moving. No errors get printed, but no output on the steering wheel as well. That's why the hello world does not work.

I see that you use the HID write method in the API, but I do not have info about how to format the data for the G27. If you could share the documentation you have for driving the G27 I can do some tests, I think that working with LEDs would be the easiest way: once it is solved on the LEDs I am sure everything else will get fixed as well.

Let me know if there is something I can do in order to help, or if something about this familiar issue comes into you mind!

Thank you very much!

**Comment by ForestMist** [comment]
New build to test at https://github.com/ForestMist/logitech-g27/releases/tag/v1.0.6

I found that the HID values where coming back as one of two numbers on my system. Like sometimes it would pass one call to findWheel() and then bomb out in the second call.

Can you try running`test-leds.js` in the test directory and tell me if that works for you? If not, can you send me your output of `hid-devices.js`? If you run `hid-devices.js` multiple times and get back different productId values for the logitech wheel, I would appreciate a copy of every different output variant.

Oh and if you don't see the test directory, that is a bug affecting NPM installs right now. You may have to download the missing directory / files from here on GitHub.

**Comment by ForestMist** [comment]
A brain cell just fired and I remembered this resource...

https://www.gtplanet.net/forum/threads/g27-g25-dfgt-undocumented-wheel-lock-settings-guide.286646/

Useful to reset your wheel into 900 degree mode in case you ever jam a bunch of buttons (like I did) and get it into a weird mode.

Any luck with the v1.0.6 build? Since I can't replicate your writing issue on my wheel I'm kinda out of stuff to try. :o

**Comment by enricodente** [comment]
Hi Daniel,
I have tested build 1.0.6 but it did not solve the issues, sorry for the delay!!!
My test code is the following:

`var g = require('logitech-g27');

g.connect(function(err) {

	g.on('pedals-gas', function(val) {
		console.log("Gas Pedal " + val)
		g.leds(val)
	}).on('wheel-turn', function(val) {
	  console.log('Wheel turned to ' + val)
	}).on('wheel-shift_left', function(val) {
	  console.log('Shifted left ' + val)
	}).on('wheel-shift_right', function(val) {
	  console.log('Shifted right ' + val)
	}).on('wheel-button_1', function(val) {
	  console.log('BTN1 ' + val)
	}).on('wheel-button_2', function(val) {
	  console.log('BTN2 ' + val)
	}).on('wheel-button_3', function(val) {
	  console.log('BTN3 ' + val)
	}).on('wheel-button_4', function(val) {
	  console.log('BTN4 ' + val)
	}).on('wheel-button_5', function(val) {
	  console.log('BTN5 ' + val)
	}).on('wheel-button_6', function(val) {
	  console.log('BTN6 ' + val)
	})
	
})`

All the console logs are perfect, I read pedal value, button presses (1) and releases (0). The leds do not work at all, but they are ok because testing them with other softwares like FanaLeds I can get them work.
Also, there is the strange start behavior: after I connect it it calibrates and goes in middle position. Using the previous code, at the first interaction with the G27 (button press, pedal press, touching the steering wheel, causing a trigger of the wheel-turn), the steering wheel will pass from the starting ~50 position, to ~100 position. As said, all the other successive events are triggered successfully, but no leds and no motor controls at all.

Running test-leds.js results in:
- The console log blocked to "One moment please" until I trigger the first event. At that point the "Wheel ready" message appears together with the coloured asterisks (very nice! 👍 ). This might be a good point, should the "Wheel ready message" show at the wheel connection instead of getting executed just after the first event triggered?
- The wheel turns again from position ~50 to ~100 as in my tests at the first pedal press, then stays there forever until next calibration (unplug/plug USB).

Here is the output of hid-devices.js, productId is stable 49819 running multiple times:
`  { vendorId: 1133,
    productId: 49819,
    path: '\\\\?\\hid#vid_046d&pid_c29b#6&b3d15e8&1&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
    product: 'G27 Racing Wheel',
    release: 4664,
    interface: -1,
    usagePage: 1,
    usage: 4 }`

I think that the last link you posted should not be related to this kind of issue.
Thanks for your help! As said, I am available for any test you may need.

**Comment by ForestMist** [comment]
Output of hid-devices.js looks good. Guessing this is a Windows computer? Can you tell me the OS version?

**Comment by ForestMist** [comment]
I ran your test code on my Mac and the LEDs are happy when the gas is pressed. So nothing wrong with that code.

Gonna go grab a Windows computer to see what it thinks next.

**Comment by ForestMist** [comment]
Good news. I have the same issue on Windows. Wheel goes all the way right and the LEDs are not responding to the gas pedal.

**Comment by ForestMist** [comment]
Aha, If I prepend the `device.write()` statements in `code\index.js` with `0x00, ` the wheel doesn't go crazy and the LEDs work.

**Comment by ForestMist** [comment]
There is good info about this upstream problem at https://github.com/node-hid/node-hid/issues/187

I should have updated code with a workaround for you to test a bit later today. ^_^

**Comment by ForestMist** [comment]
Note to self. Document new `relayOS()` function.

**Comment by ForestMist** [comment]
Okey dokey. Grab yourself a copy of version 1.0.7 via https://github.com/ForestMist/logitech-g27/archive/master.zip and let me know if that works better.

The latest build is happy on my Mac, Windows, and Ubuntu machines so I'm very hopeful it will work on your computers too. ^_^

**Comment by enricodente** [comment]
That's GREAT!

Yes I confirm I was having issues on a Windows machine.

Looking forward to test it, I let you know very soon :-)

**Comment by enricodente** [comment]
Confirm the updated library to be working.

Have not tested the motor controls yet, but every other problem seems to be gone! :-)

Thumbs up for you Daniel!

**Comment by ForestMist** [comment]
Wonderful. Thanks for sticking with the extended troubleshooting. ^_^
